[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "getBISy"
authors = [
    {name = "Matthew Potts", email = "matthew-potts@live.com"}
]
description = "package description"
version = "0.0.1"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    anyio==4.10.0
    appdirs==1.4.4
    appnope==0.1.4
    asttokens==3.0.0
    certifi==2025.1.31
    charset-normalizer==3.4.1
    comm==0.2.2
    debugpy==1.8.13
    decorator==5.2.1
    executing==2.2.0
    h11==0.16.0
    httpcore==1.0.9
    httpx==0.26.0
    ibind==0.1.12
    idna==3.10
    ipykernel==6.29.5
    ipython==9.0.2
    ipython_pygments_lexers==1.1.1
    jedi==0.19.2
    Jinja2==3.1.6
    jupyter_client==8.6.3
    jupyter_core==5.7.2
    MarkupSafe==3.0.2
    matplotlib-inline==0.1.7
    nest-asyncio==1.6.0
    numpy==1.26.4
    packaging==24.2
    pandas==2.2.3
    parso==0.8.4
    pexpect==4.9.0
    platformdirs==4.3.6
    prompt_toolkit==3.0.50
    psutil==7.0.0
    ptyprocess==0.7.0
    pure_eval==0.2.3
    pycryptodome==3.21.0
    pyee==11.1.0
    Pygments==2.19.1
    pyhumps==3.8.0
    PyMySQL==1.1.1
    python-dateutil==2.9.0.post0
    pytz==2025.2
    PyYAML==6.0.2
    pyzmq==26.2.1
    refinitiv-data==1.6.2
    requests==2.32.3
    scipy==1.12.0
    simplejson==3.20.1
    six==1.17.0
    sniffio==1.3.1
    stack-data==0.6.3
    tenacity==8.5.0
    tornado==6.4.2
    traitlets==5.14.3
    typing_extensions==4.14.1
    tzdata==2025.2
    urllib3==2.3.0
    watchdog==2.3.1
    wcwidth==0.2.13
    websocket-client==1.8.0
]